const resources: IResource[] = [
  {
    id: "stone",
    type: "material",
    points: 0,
    minQuantity: 0,
    maxQuantity: 30,
    showWhenHasConstructionId: ["stone-storage"],
  },
  {
    id: "ore",
    type: "material",
    points: 0,
    minQuantity: 0,
    maxQuantity: 30,
    showWhenHasConstructionId: ["ore-storage"],
  },
  // * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  {
    id: "dog",
    type: "animal",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "sheep",
    type: "animal",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "donkey",
    type: "animal",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "boar",
    type: "animal",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "cattle",
    type: "animal",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  // * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  {
    id: "grain",
    type: "food",
    points: 0.5,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "vegetable",
    type: "food",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "gold",
    type: "food",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "ruby",
    type: "food",
    points: 1,
    minQuantity: 0,
    maxQuantity: 30,
  },
  {
    id: "beggingMarker",
    type: "food",
    points: -3,
    minQuantity: 0,
    maxQuantity: 20,
  },
  // * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  {
    id: "smallPasture",
    type: "land",
    points: 2,
    minQuantity: 0,
    maxQuantity: 12,
  },
  {
    id: "largePasture",
    type: "land",
    points: 4,
    minQuantity: 0,
    maxQuantity: 6,
  },
  {
    id: "oreMine",
    type: "land",
    points: 3,
    minQuantity: 0,
    maxQuantity: 5,
  },
  {
    id: "rubyMine",
    type: "land",
    points: 4,
    minQuantity: 0,
    maxQuantity: 10,
  },
  {
    id: "unusedSpace",
    type: "land",
    points: -1,
    minQuantity: 0,
    maxQuantity: 21,
  },
  {
    id: "dwelling",
    type: "land",
    points: 3,
    minQuantity: 0,
    maxQuantity: 16,
  },
  {
    id: "adjacentDwelling",
    type: "land",
    points: 0,
    minQuantity: 0,
    maxQuantity: 16,
    showWhenHasConstructionId: ["state-parlor"],
  },
  // * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  {
    id: "dwarf",
    type: "family",
    points: 1,
    minQuantity: 2,
    maxQuantity: 6,
  },
  {
    id: "armedDwarf",
    type: "family",
    points: 1,
    minQuantity: 0,
    maxQuantity: 6,
    showWhenHasConstructionId: [
      "supplies-storage",
      "weapon-storage",
      "prayer-chamber",
    ],
  },
];

export default resources;
